name: Build Menu JSON

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-menu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Generate Menu.json
        run: python build_menu.py

      - name: Commit and push Menu.json if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add Menu.json
          if git diff --cached --quiet; then
            echo 'No changes to commit'
          else
            git commit -m 'Auto-update Menu.json'
            git push
          fi
